[package]
name = "FileAwayFlow"
version = "1.0.2"
edition = "2021"

[dependencies]
pretty_env_logger = "0.5.0"
serde = { version = "1.0.217", features = ["derive"] }
tokio = { version = "1.43.0", features = ["full"] }
warp = "0.3.7"
lazy_static = "1.5.0"
